"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-25 09:54:04.542724
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_role"), "employees", ["role"], unique=False)
    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_workflow_version"),
    )
    op.create_index(op.f("ix_workflows_name"), "workflows", ["name"], unique=False)
    op.create_table(
        "employee_assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("employee_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "employee_id", name="uq_employee_assignment"),
    )
    op.create_index(
        op.f("ix_employee_assignments_employee_id"),
        "employee_assignments",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_assignments_user_id"),
        "employee_assignments",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "github_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repository", sa.String(length=300), nullable=False),
        sa.Column("account_login", sa.String(length=200), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("repository_selection", sa.String(length=40), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "provider",
            "repository",
            name="uq_github_connection_user_repository",
        ),
    )
    op.create_index(
        op.f("ix_github_connections_account_login"),
        "github_connections",
        ["account_login"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_connections_installation_id"),
        "github_connections",
        ["installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_connections_repository"),
        "github_connections",
        ["repository"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_connections_status"),
        "github_connections",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_connections_user_id"),
        "github_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "personas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("simulation_notice", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deleted')", name="ck_persona_status"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personas_owner_id"), "personas", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_personas_status"), "personas", ["status"], unique=False)
    op.create_table(
        "preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("context", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("rule", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_evidenced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "fingerprint", name="uq_preference_user_fingerprint"
        ),
    )
    op.create_index(
        op.f("ix_preferences_category"), "preferences", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_preferences_context"), "preferences", ["context"], unique=False
    )
    op.create_index(
        op.f("ix_preferences_fingerprint"), "preferences", ["fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_preferences_status"), "preferences", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_preferences_user_id"), "preferences", ["user_id"], unique=False
    )
    op.create_table(
        "skill_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_version"),
    )
    op.create_index(
        op.f("ix_skill_versions_skill_id"), "skill_versions", ["skill_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("final_output", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_employee_id"), "tasks", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_tasks_workflow_name"), "tasks", ["workflow_name"], unique=False
    )
    op.create_table(
        "memory_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("source_kind", sa.String(length=80), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "source_type", "source_id", name="uq_memory_source_provenance"
        ),
    )
    op.create_index(
        op.f("ix_memory_sources_source_id"),
        "memory_sources",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_sources_source_kind"),
        "memory_sources",
        ["source_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_sources_source_type"),
        "memory_sources",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_sources_task_id"), "memory_sources", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_sources_user_id"), "memory_sources", ["user_id"], unique=False
    )
    op.create_table(
        "preference_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("preference_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("previous_status", sa.String(length=40), nullable=False),
        sa.Column("new_status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["preferences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_preference_reviews_action"),
        "preference_reviews",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preference_reviews_preference_id"),
        "preference_reviews",
        ["preference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preference_reviews_user_id"),
        "preference_reviews",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "queue_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", name="uq_queue_job_task"),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_queue_job_user_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_queue_jobs_available_at"), "queue_jobs", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_queue_jobs_lease_expires_at"),
        "queue_jobs",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_queue_jobs_status"), "queue_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_queue_jobs_task_id"), "queue_jobs", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_queue_jobs_user_id"), "queue_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("language", sa.String(length=40), nullable=True),
        sa.Column("object_key", sa.String(length=200), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("ingestion_version", sa.String(length=80), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('uploaded', 'processing', 'ready', 'failed', 'deleting', 'deleted')",
            name="ck_source_document_status",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "persona_id", "content_sha256", name="uq_source_document_persona_content"
        ),
    )
    op.create_index(
        op.f("ix_source_documents_content_sha256"),
        "source_documents",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_owner_id"),
        "source_documents",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_persona_id"),
        "source_documents",
        ["persona_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_source_type"),
        "source_documents",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_documents_status"), "source_documents", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_source_documents_task_id"),
        "source_documents",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_events_event_type"), "task_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False
    )
    op.create_table(
        "task_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_runs_status"), "task_runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_task_runs_task_id"), "task_runs", ["task_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_run_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("proposed_output", sa.JSON(), nullable=False),
        sa.Column("final_output", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["task_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_action"), "approvals", ["action"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_index(
        op.f("ix_approvals_task_id"), "approvals", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_approvals_task_run_id"), "approvals", ["task_run_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("task_run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["task_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_id", "artifact_type", "version", name="uq_artifact_version"
        ),
    )
    op.create_index(
        op.f("ix_artifacts_artifact_type"), "artifacts", ["artifact_type"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_task_id"), "artifacts", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_task_run_id"), "artifacts", ["task_run_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("chunker_name", sa.String(length=100), nullable=False),
        sa.Column("chunker_version", sa.String(length=50), nullable=False),
        sa.Column("chunker_config_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "char_start", "char_end", name="uq_document_chunk_location"
        ),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_document_chunk_ordinal"),
    )
    op.create_index(
        op.f("ix_document_chunks_content_sha256"),
        "document_chunks",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"),
        "document_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_persona_id"),
        "document_chunks",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "persona_memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("memory_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("epistemic_status", sa.String(length=40), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("candidate_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("sensitivity", sa.String(length=40), nullable=False),
        sa.Column("visibility", sa.String(length=40), nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=200), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "epistemic_status IN ('user_asserted', 'source_verified', 'model_summary', 'model_inference', 'user_rule')",
            name="ck_persona_memory_epistemic_status",
        ),
        sa.CheckConstraint(
            "memory_type IN ('episodic', 'semantic', 'procedural', 'preference', 'relationship', 'reflection')",
            name="ck_persona_memory_type",
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'confirmed', 'rejected', 'superseded', 'deleted')",
            name="ck_persona_memory_status",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "persona_id", "candidate_fingerprint", name="uq_persona_memory_candidate"
        ),
    )
    op.create_index(
        op.f("ix_persona_memories_candidate_fingerprint"),
        "persona_memories",
        ["candidate_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_current_version_id"),
        "persona_memories",
        ["current_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_epistemic_status"),
        "persona_memories",
        ["epistemic_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_memory_type"),
        "persona_memories",
        ["memory_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_owner_id"),
        "persona_memories",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_persona_id"),
        "persona_memories",
        ["persona_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_sensitivity"),
        "persona_memories",
        ["sensitivity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_source_document_id"),
        "persona_memories",
        ["source_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memories_status"), "persona_memories", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_persona_memories_visibility"),
        "persona_memories",
        ["visibility"],
        unique=False,
    )
    op.create_table(
        "preference_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("preference_id", sa.String(length=36), nullable=False),
        sa.Column("memory_source_id", sa.String(length=36), nullable=False),
        sa.Column("extraction_method", sa.String(length=100), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_source_id"],
            ["memory_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["preferences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "preference_id", "memory_source_id", name="uq_preference_memory_source"
        ),
    )
    op.create_index(
        op.f("ix_preference_evidence_memory_source_id"),
        "preference_evidence",
        ["memory_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preference_evidence_preference_id"),
        "preference_evidence",
        ["preference_id"],
        unique=False,
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_run_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["task_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_calls_task_run_id"), "tool_calls", ["task_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_calls_tool_name"), "tool_calls", ["tool_name"], unique=False
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_run_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_name", sa.String(length=120), nullable=False),
        sa.Column("workflow_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("current_step", sa.String(length=120), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_run_id"],
            ["task_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_runs_status"), "workflow_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_task_run_id"),
        "workflow_runs",
        ["task_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_runs_workflow_name"),
        "workflow_runs",
        ["workflow_name"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("dedupe_key", sa.String(length=300), nullable=False),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("persona_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("risk_level", sa.String(length=40), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=True),
        sa.Column("before_hash", sa.String(length=64), nullable=True),
        sa.Column("after_hash", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "dedupe_key", name="uq_audit_event_owner_dedupe"
        ),
    )
    op.create_index(
        op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_approval_id"),
        "audit_events",
        ["approval_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"),
        "audit_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"),
        "audit_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_outcome"), "audit_events", ["outcome"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_owner_id"), "audit_events", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_persona_id"), "audit_events", ["persona_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_resource_id"),
        "audit_events",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_resource_type"),
        "audit_events",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "decision_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("agent_recommendation", sa.JSON(), nullable=False),
        sa.Column("user_choice", sa.String(length=60), nullable=False),
        sa.Column("user_reason", sa.Text(), nullable=True),
        sa.Column("final_outcome", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_records_approval_id"),
        "decision_records",
        ["approval_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_records_task_id"),
        "decision_records",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("original", sa.JSON(), nullable=True),
        sa.Column("revised", sa.JSON(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_approval_id"), "feedback", ["approval_id"], unique=False
    )
    op.create_index(op.f("ix_feedback_kind"), "feedback", ["kind"], unique=False)
    op.create_index(op.f("ix_feedback_task_id"), "feedback", ["task_id"], unique=False)
    op.create_table(
        "persona_memory_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("structured_summary", sa.Text(), nullable=False),
        sa.Column("metadata_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by_type", sa.String(length=40), nullable=False),
        sa.Column("created_by_id", sa.String(length=200), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("extractor_name", sa.String(length=100), nullable=False),
        sa.Column("extractor_version", sa.String(length=50), nullable=False),
        sa.Column("model_call_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["persona_memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("memory_id", "version", name="uq_persona_memory_version"),
    )
    op.create_index(
        op.f("ix_persona_memory_versions_memory_id"),
        "persona_memory_versions",
        ["memory_id"],
        unique=False,
    )
    op.create_table(
        "persona_memory_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("memory_version_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("document_chunk_id", sa.String(length=36), nullable=False),
        sa.Column("relation", sa.String(length=40), nullable=False),
        sa.Column("locator_snapshot", sa.JSON(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("excerpt_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_chunk_id"],
            ["document_chunks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["persona_memory_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "memory_version_id",
            "document_chunk_id",
            "relation",
            name="uq_persona_memory_evidence",
        ),
    )
    op.create_index(
        op.f("ix_persona_memory_evidence_document_chunk_id"),
        "persona_memory_evidence",
        ["document_chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memory_evidence_memory_version_id"),
        "persona_memory_evidence",
        ["memory_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_memory_evidence_source_document_id"),
        "persona_memory_evidence",
        ["source_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_persona_memory_evidence_source_document_id"),
        table_name="persona_memory_evidence",
    )
    op.drop_index(
        op.f("ix_persona_memory_evidence_memory_version_id"),
        table_name="persona_memory_evidence",
    )
    op.drop_index(
        op.f("ix_persona_memory_evidence_document_chunk_id"),
        table_name="persona_memory_evidence",
    )
    op.drop_table("persona_memory_evidence")
    op.drop_index(
        op.f("ix_persona_memory_versions_memory_id"),
        table_name="persona_memory_versions",
    )
    op.drop_table("persona_memory_versions")
    op.drop_index(op.f("ix_feedback_task_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_kind"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_approval_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_decision_records_task_id"), table_name="decision_records")
    op.drop_index(
        op.f("ix_decision_records_approval_id"), table_name="decision_records"
    )
    op.drop_table("decision_records")
    op.drop_index(op.f("ix_audit_events_resource_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_resource_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_persona_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_owner_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_outcome"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_approval_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_workflow_runs_workflow_name"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_task_run_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_status"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_tool_calls_tool_name"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_task_run_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(
        op.f("ix_preference_evidence_preference_id"), table_name="preference_evidence"
    )
    op.drop_index(
        op.f("ix_preference_evidence_memory_source_id"),
        table_name="preference_evidence",
    )
    op.drop_table("preference_evidence")
    op.drop_index(op.f("ix_persona_memories_visibility"), table_name="persona_memories")
    op.drop_index(op.f("ix_persona_memories_status"), table_name="persona_memories")
    op.drop_index(
        op.f("ix_persona_memories_source_document_id"), table_name="persona_memories"
    )
    op.drop_index(
        op.f("ix_persona_memories_sensitivity"), table_name="persona_memories"
    )
    op.drop_index(op.f("ix_persona_memories_persona_id"), table_name="persona_memories")
    op.drop_index(op.f("ix_persona_memories_owner_id"), table_name="persona_memories")
    op.drop_index(
        op.f("ix_persona_memories_memory_type"), table_name="persona_memories"
    )
    op.drop_index(
        op.f("ix_persona_memories_epistemic_status"), table_name="persona_memories"
    )
    op.drop_index(
        op.f("ix_persona_memories_current_version_id"), table_name="persona_memories"
    )
    op.drop_index(
        op.f("ix_persona_memories_candidate_fingerprint"), table_name="persona_memories"
    )
    op.drop_table("persona_memories")
    op.drop_index(op.f("ix_document_chunks_persona_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index(
        op.f("ix_document_chunks_content_sha256"), table_name="document_chunks"
    )
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_artifacts_task_run_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_task_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_artifact_type"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_approvals_task_run_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_task_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_action"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_task_runs_task_id"), table_name="task_runs")
    op.drop_index(op.f("ix_task_runs_status"), table_name="task_runs")
    op.drop_table("task_runs")
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_event_type"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_index(op.f("ix_source_documents_task_id"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_status"), table_name="source_documents")
    op.drop_index(
        op.f("ix_source_documents_source_type"), table_name="source_documents"
    )
    op.drop_index(op.f("ix_source_documents_persona_id"), table_name="source_documents")
    op.drop_index(op.f("ix_source_documents_owner_id"), table_name="source_documents")
    op.drop_index(
        op.f("ix_source_documents_content_sha256"), table_name="source_documents"
    )
    op.drop_table("source_documents")
    op.drop_index(op.f("ix_queue_jobs_user_id"), table_name="queue_jobs")
    op.drop_index(op.f("ix_queue_jobs_task_id"), table_name="queue_jobs")
    op.drop_index(op.f("ix_queue_jobs_status"), table_name="queue_jobs")
    op.drop_index(op.f("ix_queue_jobs_lease_expires_at"), table_name="queue_jobs")
    op.drop_index(op.f("ix_queue_jobs_available_at"), table_name="queue_jobs")
    op.drop_table("queue_jobs")
    op.drop_index(
        op.f("ix_preference_reviews_user_id"), table_name="preference_reviews"
    )
    op.drop_index(
        op.f("ix_preference_reviews_preference_id"), table_name="preference_reviews"
    )
    op.drop_index(op.f("ix_preference_reviews_action"), table_name="preference_reviews")
    op.drop_table("preference_reviews")
    op.drop_index(op.f("ix_memory_sources_user_id"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_task_id"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_source_type"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_source_kind"), table_name="memory_sources")
    op.drop_index(op.f("ix_memory_sources_source_id"), table_name="memory_sources")
    op.drop_table("memory_sources")
    op.drop_index(op.f("ix_tasks_workflow_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_employee_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_skill_versions_skill_id"), table_name="skill_versions")
    op.drop_table("skill_versions")
    op.drop_index(op.f("ix_preferences_user_id"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_status"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_fingerprint"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_context"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_category"), table_name="preferences")
    op.drop_table("preferences")
    op.drop_index(op.f("ix_personas_status"), table_name="personas")
    op.drop_index(op.f("ix_personas_owner_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(
        op.f("ix_github_connections_user_id"), table_name="github_connections"
    )
    op.drop_index(op.f("ix_github_connections_status"), table_name="github_connections")
    op.drop_index(
        op.f("ix_github_connections_repository"), table_name="github_connections"
    )
    op.drop_index(
        op.f("ix_github_connections_installation_id"), table_name="github_connections"
    )
    op.drop_index(
        op.f("ix_github_connections_account_login"), table_name="github_connections"
    )
    op.drop_table("github_connections")
    op.drop_index(
        op.f("ix_employee_assignments_user_id"), table_name="employee_assignments"
    )
    op.drop_index(
        op.f("ix_employee_assignments_employee_id"), table_name="employee_assignments"
    )
    op.drop_table("employee_assignments")
    op.drop_index(op.f("ix_workflows_name"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_table("users")
    op.drop_table("skills")
    op.drop_index(op.f("ix_employees_role"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
